apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webapp.fullname" . }}-ingress
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "webapp.fullname" . }}-frontend
            port:
              number: {{ .Values.frontend.port }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "webapp.fullname" . }}-backend
            port:
              number: {{ .Values.backend.port }}
