apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: webapp
data:
  HTTP_PORT: "8080"
  index.html: |
    <html>
    <head>From ConfigMap</head>
    <body>
      <h1>Hello from ConfigMap!</h1>
    </body>
    </html>
